### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by ShellyGolden** [redhat-beyond/Xpense#12]
#11

**Comment by LiorKGOW** [comment]
issue can be closed

**Comment by adiabramovitch** [comment]
You should update this file as required in the first demo explanation.

**Comment by LiorKGOW** [comment]
> @LiorKGOW  @ShellyGolden  You should update this file as required in the first demo explanation. 

Rony is responsible to fix the file
It is written in the tasks for the next meeting

**Comment by ShellyGolden** [comment]
#17
